### ISSUE TITLE
Upgrade for current seed master

### ISSUE THREAD

**Issue by akhilman** [seed-rs/seed-rs.org#43]
I am updating the code so that I can fix the https://github.com/seed-rs/seed/issues/364 .

**Comment by akhilman** [comment]
@MartinKavik I have this error message/ Everything works as expected if I delete this overlay in browser. How to fix this?
![image](https://user-images.githubusercontent.com/180812/80607893-3cd05080-8a60-11ea-9739-3d27ac1de6cb.png)

**Comment by MartinKavik** [comment]
- It looks like a popular error - https://github.com/webpack/webpack/issues/196. 
- I think we can ignore it - try to disable it with https://github.com/webpack/webpack/issues/196#issuecomment-620227719.
 - I can't reproduce it on my machine (at least with the current `yarn.lock`).

**Comment by akhilman** [comment]
What to do with `generated::css_classes::C` and new `C!` macro?

**Comment by MartinKavik** [comment]
Is compiler sad because of the name conflict?

**Comment by akhilman** [comment]
Actually compiler is totally fine with the name similarity.

**Comment by MartinKavik** [comment]
I hoped that there won't be any problems - nice.
So... I suggest to do nothing - we can decide what to do with it in the future (if ever).
