### ISSUE TITLE
Show warning in pre-rendered page.

### ISSUE THREAD

**Issue by akhilman** [seed-rs/seed-rs.org#51]
If seed.org is open in a browser with JavaScript disabled or without WebAssembly support, then searching and switching the color scheme does not work quietly. We should display a warning that the browser does not support WebAssembly.

**Comment by MartinKavik** [comment]
Feel free to send a PR.

**Comment by akhilman** [comment]
Is there a way to distinguish a pre-rendering puppet session from a
real browser from within the seed?

**Comment by MartinKavik** [comment]
https://github.com/seed-rs/seed-rs.org/blob/911a48422189b917e52739a7bcc0dafa82c3b932/crate/src/lib.rs#L60-L63
