### ISSUE TITLE
Todo / view / step 11 confusion

### ISSUE THREAD

**Issue by tocklime** [seed-rs/seed-rs.org#59]
theres  a bit of a wrinkle on todo app doc, view page, section 11. you show the changed view() and view_filters(), but not the changed view_footer(). Section 12 then immediately changes view_footer again, so it sorts itself out, but in theory I can't get the code to compile between sections 11 and 12 (without knowing what I'm doing and fixing view_footer() ).

**Comment by MartinKavik** [comment]
Thanks! Could you fix it please?
Also `fn view_footer(tod...` in step 12. has an unnecessary indentation - could you fix it, too, please?
