### ISSUE TITLE
todo / update - suggest changing order of steps.

### ISSUE THREAD

**Issue by tocklime** [seed-rs/seed-rs.org#62]
The first item we implement is toggle todo, then remove todo. But we don't actually get to create todo until step 4. I suggest moving steps 3 (new todo title updated) and 4 (create todo) up to the top so that when we get to the toggle and remove, I can immediately see them have an effect.

Either that or earlier on in the tutorial, have the default model start with some pre-existing todos. (see also #60 )

**Comment by tocklime** [comment]
similarly, SelectTodo should come before SelectedTodoTitleChanged.

**Comment by tocklime** [comment]
nevermind, just found the `add_mock_data` step which I missed....

**Comment by tocklime** [comment]
Actually, I think there might be something here, especially with the SelectTodo and SelectedTodoTitleChanged.

**Comment by MartinKavik** [comment]
I tried to order those steps from the easiest to the most complex ones, but I don't have a strong opinion about ordering. Feel free to reorder it as it makes sense to you.
