### ISSUE TITLE
[feature request] - tutorial webpage next-prev button

### ISSUE THREAD

**Issue by eisenhaus335** [seed-rs/seed-rs.org#63]
Hello,
May we get feature that allow us to press key to navigate the tutorial webpage? Its will be useful to navigate the page

**Comment by MartinKavik** [comment]
You should be able to go to the next and previous guide by pressing right and left arrow on your keyboard. https://seed-rs.org/

**Comment by eisenhaus335** [comment]
sorry i just forgot to click the page window thats explain why i cant press it
thanks gonna close this issue

**Comment by MartinKavik** [comment]
> sorry i just forgot to click the page window thats explain why i cant press it

I've implemented key navigation after your suggestion. Thanks for the tip!

**Comment by MartinKavik** [comment]
https://github.com/seed-rs/seed-rs.org/pull/64
