### ISSUE TITLE
Light mode flash before the dark one

### ISSUE THREAD

**Issue by MartinKavik** [seed-rs/seed-rs.org#7]
The website is really good! Thanks! 
The only small problem is that if you switch to dark mode and refresh the page, it first renders in light mode, then switches.

_Originally posted by @tiberiusferreira in https://github.com/seed-rs/seed/issues/303#issuecomment-562649852_

**Comment by MartinKavik** [comment]
Default light mode is prerendered. So it changes once the wasm is loaded and Seed choose the right mode according to the local storage value.

One solution can be to move switching logic from Rust to JS and inline it into HTML. What do you think?

**Comment by tiberiusferreira** [comment]
This is a good idea and does solve the problem, but since it is such a small problem I'd prefer to keep the code in Rust which makes it easier for newcomers to follow what's going on, even if that means the flashing keeps happening.

**Comment by MartinKavik** [comment]
I agree. Closing, we can reopen it once we find a Rust-only solution.
